#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

log() { printf "[setup] %s\n" "$*"; }
fail() { printf "[setup] ERROR: %s\n" "$*" >&2; exit 1; }

is_wsl() {
  grep -qi microsoft /proc/sys/kernel/osrelease
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

require_wsl_systemd() {
  if ! is_wsl; then
    log "WSL2 not detected. Proceeding anyway."
    return
  fi

  if ! command -v systemctl >/dev/null 2>&1; then
    fail "systemctl not found. Enable systemd in WSL2 and restart WSL."
  fi

  if ! systemctl is-system-running >/dev/null 2>&1; then
    cat <<'MSG' >&2
[setup] systemd is not running in WSL2.
Enable by creating /etc/wsl.conf with:

[boot]
systemd=true

Then restart WSL.
MSG
    exit 1
  fi
}

require_cmd node
require_cmd npm
require_cmd cloudflared
require_cmd python3

require_wsl_systemd

NODE_BIN=$(command -v node)
CLOUDFLARED_BIN=$(command -v cloudflared)

if ! command -v smartthings >/dev/null 2>&1; then
  log "SmartThings CLI not found. You can create the OAuth app in Developer Workspace."
fi

log "Checking Cloudflare login"
if [ ! -f "$HOME/.cloudflared/cert.pem" ]; then
  log "Cloudflare login required. Opening login flow."
  cloudflared tunnel login
fi

TUNNEL_NAME=${TUNNEL_NAME:-smartthings-mcp}
HOSTNAME=${HOSTNAME:-}
PORT=${PORT:-8080}

if [ -z "$HOSTNAME" ]; then
  read -rp "Public hostname (e.g. st-mcp.example.com): " HOSTNAME
fi

if [ -z "$HOSTNAME" ]; then
  fail "HOSTNAME is required"
fi

log "Resolving tunnel ID"
TUNNEL_ID=$(cloudflared tunnel list --output json | python3 - <<PY
import json,sys
name = "$TUNNEL_NAME"
try:
    data = json.load(sys.stdin)
except Exception:
    data = []
for t in data:
    if t.get("name") == name:
        print(t.get("id", ""))
        break
PY
)

if [ -z "$TUNNEL_ID" ]; then
  log "Creating tunnel $TUNNEL_NAME"
  cloudflared tunnel create "$TUNNEL_NAME" >/dev/null
  TUNNEL_ID=$(cloudflared tunnel list --output json | python3 - <<PY
import json,sys
name = "$TUNNEL_NAME"
try:
    data = json.load(sys.stdin)
except Exception:
    data = []
for t in data:
    if t.get("name") == name:
        print(t.get("id", ""))
        break
PY
)
fi

if [ -z "$TUNNEL_ID" ]; then
  fail "Failed to resolve tunnel ID"
fi

CRED_FILE="$HOME/.cloudflared/${TUNNEL_ID}.json"
if [ ! -f "$CRED_FILE" ]; then
  fail "Tunnel credentials not found at $CRED_FILE"
fi

log "Configuring Cloudflare tunnel"
cat > "$ROOT_DIR/cloudflared/config.yml" <<CFG
# Auto-generated by setup.sh

tunnel: $TUNNEL_ID
credentials-file: $CRED_FILE

ingress:
  - hostname: $HOSTNAME
    service: http://localhost:$PORT
  - service: http_status:404
CFG

cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" >/dev/null || true

if [ ! -f "$ROOT_DIR/.env" ]; then
  log "Creating .env"
  cat > "$ROOT_DIR/.env" <<ENV
PUBLIC_URL=https://$HOSTNAME
PORT=$PORT
SMARTTHINGS_WEBHOOK_PATH=/smartthings
MCP_HTTP_PATH=/mcp
SMARTTHINGS_CLIENT_ID=
SMARTTHINGS_CLIENT_SECRET=
SMARTTHINGS_OAUTH_TOKEN_URL=https://api.smartthings.com/oauth/token
SMARTTHINGS_OAUTH_AUTHORIZE_URL=https://api.smartthings.com/oauth/authorize
SMARTTHINGS_API_BASE_URL=https://api.smartthings.com/v1
SMARTTHINGS_VERIFY_SIGNATURES=true
SIGNATURE_TOLERANCE_SEC=300
ALLOWED_MCP_HOSTS=localhost,127.0.0.1,$HOSTNAME
TOKEN_STORE_PATH=$ROOT_DIR/data/token-store.json
OAUTH_SCOPES=r:locations:* r:devices:* x:devices:* r:scenes:* x:scenes:* r:rules:* w:rules:*
OAUTH_REDIRECT_PATH=/oauth/callback
LOG_LEVEL=info
ENV
fi

CLIENT_ID=${SMARTTHINGS_CLIENT_ID:-}
CLIENT_SECRET=${SMARTTHINGS_CLIENT_SECRET:-}

if [ -z "$CLIENT_ID" ]; then
  read -rp "SmartThings Client ID: " CLIENT_ID
fi
if [ -z "$CLIENT_SECRET" ]; then
  read -rp "SmartThings Client Secret: " CLIENT_SECRET
fi

if [ -z "$CLIENT_ID" ] || [ -z "$CLIENT_SECRET" ]; then
  fail "SmartThings Client ID/Secret required"
fi

sed -i "s|^SMARTTHINGS_CLIENT_ID=.*|SMARTTHINGS_CLIENT_ID=$CLIENT_ID|" "$ROOT_DIR/.env"
sed -i "s|^SMARTTHINGS_CLIENT_SECRET=.*|SMARTTHINGS_CLIENT_SECRET=$CLIENT_SECRET|" "$ROOT_DIR/.env"

log "Installing dependencies"
cd "$ROOT_DIR"
npm install
npm run build

log "Writing systemd services"
APP_SERVICE=/etc/systemd/system/smartthings-mcp.service
TUNNEL_SERVICE=/etc/systemd/system/cloudflared-smartthings-mcp.service

sudo tee "$TUNNEL_SERVICE" >/dev/null <<SERVICE
[Unit]
Description=Cloudflare Tunnel for SmartThings MCP
After=network.target

[Service]
Type=simple
User=$USER
ExecStart=$CLOUDFLARED_BIN --config $ROOT_DIR/cloudflared/config.yml tunnel run
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
SERVICE

sudo tee "$APP_SERVICE" >/dev/null <<SERVICE
[Unit]
Description=SmartThings MCP Server
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$ROOT_DIR
EnvironmentFile=$ROOT_DIR/.env
ExecStart=$NODE_BIN dist/index.js
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
SERVICE

sudo systemctl daemon-reload
sudo systemctl enable --now cloudflared-smartthings-mcp.service
sudo systemctl enable --now smartthings-mcp.service

log "Setup complete"
log "Next: open .env and set SMARTTHINGS_CLIENT_ID/SMARTTHINGS_CLIENT_SECRET"
log "Then restart: sudo systemctl restart smartthings-mcp.service"
